version: 2

sources:
  - name: raw
    database: LeWagon-SQL-Fereshteh-1E  # Replace with the actual name of your database if known.
    schema: gz_raw_data    # Replace with the actual name of your schema if known.
    tables:
      - name: raw_gz_sales
        identifier: sales
      - name: raw_gz_product
        identifier: product
      - name: raw_gz_ship
        identifier: ship