version: 2

sources:
  - name: gz_raw_data
    tables: 
      - name: sales
        identifier: raw_gz_sales
        columns:
          - name: orders_id
            tests:
            - unique
            
                
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
            - unique
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
            - unique
        