version: 2

sources:
  - name: gz_raw_data
    tables: 
      - name: sales
        identifier: raw_gz_sales
        


            
                
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
            - unique
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
            - unique
        

        
models:
  - name: sales
    description: "This is the sales table."
    
    freshness:
      warn_after:
        count: 90
        period: day
    loaded_at_field: "CAST(your_timestamp_column_here AS TIMESTAMP)"
R